export { default as Beech } from "./Beech";
export { default as Birch } from "./Birch";
export { default as DouglasFir } from "./DouglasFir";
export { default as HorseChestnut } from "./HorseChestnut";
export { default as Linden } from "./Linden";
export { default as Oak } from "./Oak";
export { default as Sapling } from "./Sapling";
export { default as SilverFir } from "./SilverFir";
export { default as Sycamore } from "./Sycamore";
